pub enum Instruction {
    Add(ArithmeticTarget),
    AddC(ArithmeticTarget),
    And(ArithmeticTarget),
    Xor(ArithmeticTarget),
    Or(ArithmeticTarget),
    LoadB(Target),
    LoadC(Target),
    LoadD(Target),
    LoadE(Target),
    LoadH(Target),
    LoadL(Target),
    LoadA(Target),
    LoadHL(Target),
    End,
}

pub enum ArithmeticTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    HL,
}

pub enum Target {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    HL,
}

impl Instruction {
    pub fn from_byte(byte: u8) -> Option<Instruction> {
        match byte {
            0x00 => Some(Instruction::End),
            0x40 => Some(Instruction::LoadB(Target::B)),
            0x41 => Some(Instruction::LoadB(Target::C)),
            0x42 => Some(Instruction::LoadB(Target::D)),
            0x43 => Some(Instruction::LoadB(Target::E)),
            0x44 => Some(Instruction::LoadB(Target::H)),
            0x45 => Some(Instruction::LoadB(Target::L)),
            0x46 => Some(Instruction::LoadB(Target::HL)),
            0x47 => Some(Instruction::LoadB(Target::A)),
            0x48 => Some(Instruction::LoadC(Target::B)),
            0x49 => Some(Instruction::LoadC(Target::C)),
            0x4A => Some(Instruction::LoadC(Target::D)),
            0x4B => Some(Instruction::LoadC(Target::E)),
            0x4C => Some(Instruction::LoadC(Target::H)),
            0x4D => Some(Instruction::LoadC(Target::L)),
            0x4E => Some(Instruction::LoadC(Target::HL)),
            0x4F => Some(Instruction::LoadC(Target::A)),

            0x50 => Some(Instruction::LoadD(Target::B)),
            0x51 => Some(Instruction::LoadD(Target::C)),
            0x52 => Some(Instruction::LoadD(Target::D)),
            0x53 => Some(Instruction::LoadD(Target::E)),
            0x54 => Some(Instruction::LoadD(Target::H)),
            0x55 => Some(Instruction::LoadD(Target::L)),
            0x56 => Some(Instruction::LoadD(Target::HL)),
            0x57 => Some(Instruction::LoadD(Target::A)),
            0x58 => Some(Instruction::LoadE(Target::B)),
            0x59 => Some(Instruction::LoadE(Target::C)),
            0x5A => Some(Instruction::LoadE(Target::D)),
            0x5B => Some(Instruction::LoadE(Target::E)),
            0x5C => Some(Instruction::LoadE(Target::H)),
            0x5D => Some(Instruction::LoadE(Target::L)),
            0x5E => Some(Instruction::LoadE(Target::HL)),
            0x5F => Some(Instruction::LoadE(Target::A)),

            0x60 => Some(Instruction::LoadH(Target::B)),
            0x61 => Some(Instruction::LoadH(Target::C)),
            0x62 => Some(Instruction::LoadH(Target::D)),
            0x63 => Some(Instruction::LoadH(Target::E)),
            0x64 => Some(Instruction::LoadH(Target::H)),
            0x65 => Some(Instruction::LoadH(Target::L)),
            0x66 => Some(Instruction::LoadH(Target::HL)),
            0x67 => Some(Instruction::LoadH(Target::A)),
            0x68 => Some(Instruction::LoadL(Target::B)),
            0x69 => Some(Instruction::LoadL(Target::C)),
            0x6A => Some(Instruction::LoadL(Target::D)),
            0x6B => Some(Instruction::LoadL(Target::E)),
            0x6C => Some(Instruction::LoadL(Target::H)),
            0x6D => Some(Instruction::LoadL(Target::L)),
            0x6E => Some(Instruction::LoadL(Target::HL)),
            0x6F => Some(Instruction::LoadL(Target::A)),

            0x70 => Some(Instruction::LoadHL(Target::B)),
            0x71 => Some(Instruction::LoadHL(Target::C)),
            0x72 => Some(Instruction::LoadHL(Target::D)),
            0x73 => Some(Instruction::LoadHL(Target::E)),
            0x74 => Some(Instruction::LoadHL(Target::H)),
            0x75 => Some(Instruction::LoadHL(Target::L)),
            0x77 => Some(Instruction::LoadHL(Target::A)),
            0x78 => Some(Instruction::LoadA(Target::B)),
            0x79 => Some(Instruction::LoadA(Target::C)),
            0x7A => Some(Instruction::LoadA(Target::D)),
            0x7B => Some(Instruction::LoadA(Target::E)),
            0x7C => Some(Instruction::LoadA(Target::H)),
            0x7D => Some(Instruction::LoadA(Target::L)),
            0x7E => Some(Instruction::LoadA(Target::HL)),
            0x7F => Some(Instruction::LoadA(Target::A)),

            0x80 => Some(Instruction::Add(ArithmeticTarget::B)),
            0x81 => Some(Instruction::Add(ArithmeticTarget::C)),
            0x82 => Some(Instruction::Add(ArithmeticTarget::D)),
            0x83 => Some(Instruction::Add(ArithmeticTarget::E)),
            0x84 => Some(Instruction::Add(ArithmeticTarget::H)),
            0x85 => Some(Instruction::Add(ArithmeticTarget::L)),
            0x86 => Some(Instruction::Add(ArithmeticTarget::HL)),
            0x87 => Some(Instruction::Add(ArithmeticTarget::A)),
            0x88 => Some(Instruction::AddC(ArithmeticTarget::B)),
            0x89 => Some(Instruction::AddC(ArithmeticTarget::C)),
            0x8A => Some(Instruction::AddC(ArithmeticTarget::D)),
            0x8B => Some(Instruction::AddC(ArithmeticTarget::E)),
            0x8C => Some(Instruction::AddC(ArithmeticTarget::H)),
            0x8D => Some(Instruction::AddC(ArithmeticTarget::L)),
            0x8E => Some(Instruction::AddC(ArithmeticTarget::HL)),
            0x8F => Some(Instruction::AddC(ArithmeticTarget::A)),

            0xA0 => Some(Instruction::And(ArithmeticTarget::B)),
            0xA1 => Some(Instruction::And(ArithmeticTarget::C)),
            0xA2 => Some(Instruction::And(ArithmeticTarget::D)),
            0xA3 => Some(Instruction::And(ArithmeticTarget::E)),
            0xA4 => Some(Instruction::And(ArithmeticTarget::H)),
            0xA5 => Some(Instruction::And(ArithmeticTarget::L)),
            0xA6 => Some(Instruction::And(ArithmeticTarget::HL)),
            0xA7 => Some(Instruction::And(ArithmeticTarget::A)),
            0xA8 => Some(Instruction::Xor(ArithmeticTarget::B)),
            0xA9 => Some(Instruction::Xor(ArithmeticTarget::C)),
            0xAA => Some(Instruction::Xor(ArithmeticTarget::D)),
            0xAB => Some(Instruction::Xor(ArithmeticTarget::E)),
            0xAC => Some(Instruction::Xor(ArithmeticTarget::H)),
            0xAD => Some(Instruction::Xor(ArithmeticTarget::L)),
            0xAE => Some(Instruction::Xor(ArithmeticTarget::HL)),
            0xAF => Some(Instruction::Xor(ArithmeticTarget::A)),

            0xB0 => Some(Instruction::Or(ArithmeticTarget::B)),
            0xB1 => Some(Instruction::Or(ArithmeticTarget::C)),
            0xB2 => Some(Instruction::Or(ArithmeticTarget::D)),
            0xB3 => Some(Instruction::Or(ArithmeticTarget::E)),
            0xB4 => Some(Instruction::Or(ArithmeticTarget::H)),
            0xB5 => Some(Instruction::Or(ArithmeticTarget::L)),
            0xB6 => Some(Instruction::Or(ArithmeticTarget::HL)),
            0xB7 => Some(Instruction::Or(ArithmeticTarget::A)),
            _ => None,
        }
    }
}
